name: Build and Deploy Code

on: [push, pull_request]
  # push:
  #   branches:
  #     - "main"
  # pull_request:
  #   branches:
  #     - "test_branch"

# https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#matrix-testing

env:
  DATABASE_HOSTNAME: localhost
  DATABASE_PORT: 5432
  DATABASE_PASSWORD: chocolate9
  DATABASE_NAME: fastapi
  DATABASE_USERNAME: postgres
  SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e8
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: 30

jobs:
  job1: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: install python version '2.x' & '3.x'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # python-version: [ '2.x', '3.x', 'pypy2.7', 'pypy3.7', 'pypy3.8' ]
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest